### ISSUE TITLE
Can I write require member?

### ISSUE THREAD

**Issue by kyubuns** [vlang-io/V#52]
V-lang is very good language!!!

Can I write require member in struct?
I think a struct which has default value is nearly equal null. (ex. User{ id: 0 } )
I don't want to exist them same as null.
What do you think?

---

Example, I want "User must have `id`".

```
struct User {
	id int /*  'require' keyword*/
}

fn main() {
	user1 := User{id: 10}
	user2 := User{} // I want this is error
}
```

**Comment by medvednikov** [comment]
Hi @kyubuns 

Yes! See this discussion:

https://github.com/vlang-io/V/issues/3#issuecomment-466788060

If a struct has at least one private int (and in your example `id` is private, since it's the default), it will be impossible to use struct initialization syntax outside the module it's defined it.

So you'll have to provide a construct method (like `new_user() User`).

**Comment by kyubuns** [comment]
Great.
Thanks!!
